#!/bin/sh

/usr/sbin/tailscale_secrets migrate || exit 1

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscale[-1]
	commit ucitrack
EOF

if [ -x /etc/init.d/tailscale-openclash-bypass ]; then
	/etc/init.d/tailscale-openclash-bypass enable
	/etc/init.d/tailscale-openclash-bypass start
fi

rm -f /tmp/luci-indexcache
exit 0
