#!/bin/sh /etc/rc.common

START=95

USE_PROCD=1

PROG=/usr/sbin/tailscale_adguard_dns_switch

service_triggers() {
	procd_add_reload_trigger "tailscale"
}

start_instance() {
	local cfg="$1"
	local enabled adguard_dns_switch_enabled std_out std_err
	local adguard_health_domain adguard_health_expected_ips
	local adguard_default_upstreams adguard_tailnet_upstreams

	config_get_bool enabled "$cfg" 'enabled' 0
	[ "$enabled" = "1" ] || {
		echo "disabled in /etc/config/tailscale"
		return 0
	}

	config_get_bool adguard_dns_switch_enabled "$cfg" 'adguard_dns_switch_enabled' 0
	[ "$adguard_dns_switch_enabled" = "1" ] || return 0

	config_get adguard_health_domain "$cfg" 'adguard_health_domain'
	config_get adguard_health_expected_ips "$cfg" 'adguard_health_expected_ips'
	config_get adguard_default_upstreams "$cfg" 'adguard_default_upstreams'
	config_get adguard_tailnet_upstreams "$cfg" 'adguard_tailnet_upstreams'

	[ -n "$adguard_health_domain" ] || {
		logger -p daemon.err -t tailscale_adguard_dns "adguard_dns_switch_enabled=1 but adguard_health_domain is not configured"
		return 0
	}
	[ -n "$adguard_health_expected_ips" ] || {
		logger -p daemon.err -t tailscale_adguard_dns "adguard_dns_switch_enabled=1 but adguard_health_expected_ips is not configured"
		return 0
	}
	[ -n "$adguard_default_upstreams" ] || {
		logger -p daemon.err -t tailscale_adguard_dns "adguard_dns_switch_enabled=1 but adguard_default_upstreams is not configured"
		return 0
	}
	[ -n "$adguard_tailnet_upstreams" ] || {
		logger -p daemon.err -t tailscale_adguard_dns "adguard_dns_switch_enabled=1 but adguard_tailnet_upstreams is not configured"
		return 0
	}

	config_get_bool std_out "$cfg" 'log_stdout' 1
	config_get_bool std_err "$cfg" 'log_stderr' 1

	procd_open_instance adguard_dns
	procd_set_param command "$PROG" --run
	procd_set_param respawn
	procd_set_param stdout "$std_out"
	procd_set_param stderr "$std_err"
	procd_close_instance
}

start_service() {
	config_load 'tailscale'
	config_foreach start_instance 'tailscale'
}
